apiVersion: v1
kind: Pod
metadata:
  name: log-writer
spec:
  containers:
    - name: writer
      image: busybox
      command: ["/bin/sh", "-c", "while true; do echo Hello from pod $(hostname) >> /logs/test.log; sleep 5; done"]
      volumeMounts:
        - name: app-logs
          mountPath: /logs
  volumes:
    - name: app-logs
      persistentVolumeClaim:
        claimName: pvc-app-logs

