apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-config
data:
  DB_HOST: mydb-service
  DB_USER: appuser
---
apiVersion: v1
kind: Secret
metadata:
  name: nodejs-secret
type: Opaque
data:
  DB_PASSWORD: c3VwZXJzZWNyZXQ=   # كلمة supersecret مشفرة بـ base64
